from pydantic import BaseModel, Field
from typing import List, Optional

class Source(BaseModel):
    id: int = Field(description="Numeric citation index starting at 1 (e.g. 1, 2, 3)")
    title: str = Field(description="Title of the web page or research document")
    url: str = Field(description="Full web URL of the source")
    domain: str = Field(description="Root web domain e.g. 'arxiv.org' or 'openai.com'")
    snippet: str = Field(description="Relevant text snippet extracted from source")
    source_type: str = Field(default="technical_blog", description="Category: 'research', 'official', 'news', 'technical_blog'")
    published_at: Optional[str] = Field(default=None, description="Publication date if available")
    relevance_score: float = Field(default=1.0, description="Relevance score (0.0 to 1.0)")

class Finding(BaseModel):
    claim: str = Field(description="Core factual claim or takeaway assertion")
    evidence: str = Field(description="Specific data point, quote, or study metric supporting the claim")
    source_ids: List[int] = Field(default_factory=list, description="List of source ID integers [1, 2] supporting this finding")

class ResearchReport(BaseModel):
    question: str = Field(description="Original user research question")
    executive_summary: str = Field(description="High-level narrative overview synthesizing core research conclusions")
    key_findings: List[Finding] = Field(default_factory=list, description="Structured key findings linked directly to source citations")
    contradictions: List[str] = Field(default_factory=list, description="Conflicting evidence or disagreements identified across sources")
    limitations: List[str] = Field(default_factory=list, description="Methodological limitations, research gaps, or scope boundaries")
    confidence_level: str = Field(default="Medium", description="System confidence: 'High', 'Medium', or 'Low'")
    conclusion: str = Field(description="Final summary outlook and future research directions")
    sources: List[Source] = Field(default_factory=list, description="Bibliography list of all sources cited in report")

class ResearchRequest(BaseModel):
    question: str = Field(description="Research question or topic to investigate")
    depth: str = Field(default="standard", description="Research depth: 'quick', 'standard', 'deep'")
    source_filter: Optional[str] = Field(default=None, description="Optional domain filter e.g. 'arxiv.org' or 'academic'")

class ResearchResponse(BaseModel):
    success: bool
    report: Optional[ResearchReport] = None
    search_queries_used: List[str] = Field(default_factory=list, description="Sub-queries generated by Query Planner")
    error: Optional[str] = None
    processing_time_sec: float = 0.0
